language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script: ./travis.sh

before_script:
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

notifications:
  email: false
